export const GAME_OVER = 'Game Over! You lose. Fortunately there always is a next game...'
export const GAME_WON = 'Well done! Your answer was correct!'
export const WHICH_COUNTRY='Which country?'
export const START_A_NEW_GAME='Start a new game?'
export const NUMBER_OF_TILES = 9
export const INTERVAL_VAL = 1000
export const TIMER_INIT = 20
export const DEFAULT_NUMBER_OF_FURTHER_ANSWER_OPTIONS = 2
export const GAMETIMER_TICK_MS = 1000